=== RomanKoff/Ans.Net10/Ans.Net10.Web/Sitemap/MapPages.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="MapPages"
           targetNamespace="urn:ans:net10:web:map-pages"
           elementFormDefault="qualified"
           xmlns="urn:ans:net10:web:map-pages"
           xmlns:xs="http://w3.org">

	<xs:element name="pages">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="ItemType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="item" type="ItemType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="target" type="xs:string" use="optional" />
		<xs:attribute name="face" type="xs:string" use="optional" />
		<xs:attribute name="start" type="xs:boolean" use="optional" default="true" />
	</xs:complexType>

</xs:schema>

=== RomanKoff/Ans.Net10/Ans.Net10.CMS/Views/Nodes/it2/_map-pages.xml
<?xml version="1.0" encoding="utf-8"?>
<pages xmlns="urn:ans:net10:web:map-pages"
	   xmlns:xsi="http://w3.org"
	   xsi:schemaLocation="urn:ans:net10:web:map-pages MapPages.xsd">

	<item target="brand" face="Фирстиль">
		<item target="colors" face="Цвета|Основные {0}" />
		<item target="logo-guap" face="Логотипы ГУАП" />
		<item target="logo-guap-deps" face="Логотипы подразделений ГУАП" />
	</item>

	<item target="helpers" face="Helpers">
		<item target="news" face="News">
			<item target="node" face="Узел (публикации, объявления, мероприятия)" />
		</item>
	</item>

	<item target="libs" face="Libs" start="false">
		<item target="bootstrap-icons_1-11-3" />
		<item target="guap-icons_11" />
	</item>

</pages>

=== RomanKoff/Ans.Net10/Ans.Net10.CMS/Views/Nodes/mag/_map-pages.xml
<?xml version="1.0" encoding="utf-8"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns="urn:ans:net10:web:map-pages"
	   xsi:schemaLocation="urn:ans:net10:web:map-pages https://raw.githubusercontent.com/RomanKoff/Ans.Net10/refs/heads/main/Ans.Net10.Web/Sitemap/MapPages.xsd">

	<item target="brand" face="Фирстиль">
		<item target="colors" face="Цвета|Основные {0}" />
		<item target="logo-guap" face="Логотипы ГУАП" />
		<item target="logo-guap-deps" face="Логотипы подразделений ГУАП" />
	</item>

	<item target="helpers" face="Helpers">
		<item target="news" face="News">
			<item target="node" face="Узел (публикации, объявления, мероприятия)" />
		</item>
	</item>

	<item target="libs" face="Libs" start="false">
		<item target="bootstrap-icons_1-11-3" />
		<item target="guap-icons_11" />
	</item>

</pages>
